on: push
name: Test
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: octodns test
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsuses
        uses: docker://octodns/octodns/cloudflare:2023.05@sha256:762f17b63e32c2f449378fd961a3323b3f3213a9cc7cb8a22691062b0ec8e0f0
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        with:
          args: octodns-sync --config-file ./config/production.yaml
